"""Catalog of well-known merchants, to guarantee real brands are covered.

Complements the curated Canadian list in `generate_merchant_dataset.MERCHANTS` and the
merchants already present in `cc_merchants_combined.csv`. Everything here is a real
brand a Canadian cardholder plausibly sees on a statement - Canadian chains first, plus
US and global brands that bill Canadian cards (travel, streaming, e-commerce).

Category assignments follow src/cc_tool/categories.py. Where a brand spans categories the
dominant use of a *credit card* decides: Costco is Groceries (that is what people buy
there), Canadian Tire is Shopping, gas bars are Transport.
"""

EXTRA_MERCHANTS: dict[str, list[str]] = {
    "Groceries": [
        "M&M Food Market", "Marche Adonis", "Urban Fare", "Fresh St Market",
        "Stongs Market", "Coppas Fresh Market", "Vince's Market", "Starsky Foods",
        "Btrust Supermarket", "Foody Mart", "Lucky Supermarket", "Seasons Foods",
        "PA Supermarket", "Danforth Food Market", "Michael-Angelo's", "Farm Boy Express",
        "Loblaw City Market", "Atlantic Superstore", "Dominion", "Colemans",
        "Powells Supermarket", "Co-op Food Store", "Federated Co-op", "Otter Co-op",
        "Peavey Foods", "Instacart", "Voila by Sobeys", "Grocery Gateway", "SPUD",
        "Kroger", "Publix", "Albertsons", "Wegmans", "H-E-B", "Meijer", "Food Lion",
        "Giant Eagle", "Stop & Shop", "ShopRite", "Sprouts Farmers Market", "Aldi",
        "Lidl", "Piggly Wiggly", "Winn-Dixie", "Hy-Vee", "Vons", "Ralphs", "Fry's",
    ],
    "Dining": [
        "Milestones", "Joey Restaurants", "Browns Socialhouse", "State & Main",
        "Original Joes", "The Works Craft Burgers", "Pizza Nova", "Greco Pizza",
        "Pizza 73", "Fatburger", "Smokes Poutinerie", "La Belle Province",
        "Restaurant Valentine", "Chez Ashton", "Scores", "Normandin", "Mikes",
        "Casey's", "Ricky's All Day Grill", "Denny's", "IHOP", "Cracker Barrel",
        "Applebee's", "Chili's", "TGI Fridays", "Red Lobster", "Outback Steakhouse",
        "The Cheesecake Factory", "Buffalo Wild Wings", "Wingstop", "Church's Chicken",
        "Sonic Drive-In", "Del Taco", "Bojangles Chicken", "Boston Market", "Sbarro",
        "Krispy Kreme", "Cinnabon", "Auntie Anne's", "BeaverTails", "Marble Slab Creamery",
        "Menchies", "Yogen Fruz", "Sweet Jesus", "DavidsTea", "Chatime", "Gong Cha",
        "CoCo Fresh Tea", "Presotea", "Aroma Espresso Bar", "Balzacs Coffee",
        "JJ Bean Coffee", "Van Houtte", "Timothys Coffee", "Coffee Culture",
        "Tim Hortons Express", "Fionn MacCools", "The Pint", "Local Public Eatery",
        "Craft Beer Market", "Earls Kitchen", "The Canadian Brewhouse", "Wvrst",
        "Fresh Kitchen", "Copper Branch", "Kupfert & Kim", "Aloette", "Pai Northern",
        "Fantuan Delivery", "Ritual", "Instacart Restaurants",
    ],
    "Transport": [
        "Circle K", "Couche-Tard", "Irving Oil", "Costco Gas", "Domo Gasoline",
        "Mobil Gas Bar", "Race Trac", "Speedway", "Wawa", "Sheetz", "BP", "Sunoco",
        "Marathon Petroleum", "Citgo", "Arco", "Valero", "Phillips 66", "Casey's General",
        "UP Express", "STO Gatineau", "Transit Windsor", "Saskatoon Transit",
        "Regina Transit", "Guelph Transit", "London Transit", "Kingston Transit",
        "Barrie Transit", "St Catharines Transit", "Thunder Bay Transit",
        "Strathcona Transit", "Lethbridge Transit", "Red Deer Transit", "Whitehorse Transit",
        "Lime", "Bird Scooter", "Bike Share Toronto", "Bixi Montreal", "Mobi Vancouver",
        "Roam Transit", "Coach Canada", "Ontario Northland", "Rider Express",
        "Maritime Bus", "DriveTest", "Carshare Atlantic", "Pacific Parking",
        "EasyPark", "Wheels Parking", "Parkopedia", "SpotHero", "Petro Points",
    ],
    "Travel": [
        "Swoop", "Lynx Air", "Air North", "Central Mountain Air", "Harbour Air",
        "Pacific Coastal Airlines", "PAL Airlines", "Canadian North", "Air Inuit",
        "United Airlines", "Air France", "KLM", "Lufthansa", "British Airways",
        "Emirates", "Qatar Airways", "Turkish Airlines", "Aer Lingus", "Icelandair",
        "Aeromexico", "Copa Airlines", "LATAM Airlines", "ANA", "Japan Airlines",
        "Korean Air", "Singapore Airlines", "Qantas", "Aeroplan", "Sunquest Vacations",
        "Motel 6", "Quality Inn", "Econo Lodge", "Wyndham Hotels", "Courtyard Marriott",
        "Residence Inn", "Hampton Inn", "DoubleTree", "Embassy Suites",
        "Homewood Suites", "Chelsea Hotel Toronto", "Shangri-La Hotel",
        "Ritz-Carlton", "InterContinental Hotels", "Le Germain Hotel", "Alt Hotel",
        "Sheraton Centre", "Hotel X Toronto", "Fogo Island Inn", "Banff Springs",
        "Chateau Lake Louise", "Jasper Park Lodge", "Rocky Mountain Sky",
        "Via Rail Canada", "Rail Europe", "Contiki", "G Adventures", "Flight Centre",
        "Cheapoair", "Skyscanner", "Momondo", "Agoda", "Hostelworld",
    ],
    "Shopping": [
        "Holt Renfrew", "Harry Rosen", "Moores Clothing", "Tip Top Tailors", "RW&CO",
        "Suzy Shier", "Laura Canada", "Melanie Lyne", "Northern Reflections", "Cleo",
        "Rickis", "Bootlegger", "Warehouse One", "Mark's Work Wearhouse",
        "American Eagle", "Abercrombie & Fitch", "Hollister", "Forever 21",
        "Banana Republic", "J Crew", "Talbots", "Anthropologie", "Free People",
        "Lands End", "Eddie Bauer", "Columbia Sportswear", "Patagonia",
        "The North Face", "Under Armour", "Puma", "Reebok", "New Balance", "Skechers",
        "Foot Locker", "Browns Shoes", "Aldo", "Call It Spring", "DSW", "Town Shoes",
        "Little Burgundy", "Sunglass Hut", "Pandora Jewellery", "Swarovski",
        "Michael Hill", "Peoples Jewellers", "Charm Diamond Centres", "Birks",
        "Memory Express", "Canada Computers", "Newegg", "Apple Store",
        "Microsoft Store", "Samsung Store", "Grand & Toy", "Coles Books",
        "Party City", "Miniso", "Muji", "Etsy", "AliExpress", "Temu", "Shein",
        "Poshmark", "Value Village", "Talize", "Decathlon", "SAIL Outdoors",
        "Altitude Sports", "Frank And Oak", "Kit and Ace", "Sporting Life",
        "Nordstrom Canada", "Winners HomeSense", "Giant Tiger Store", "Target",
        "Kohls", "JCPenney", "Sears", "Wayfair Canada", "Costco Online",
        # High-frequency e-commerce that was missing as a BARE name. The catalog had
        # "Amazon.ca" and "Amazon Prime Video" but not "Amazon", so the corpus held only
        # 3 Amazon rows out of 90k - two of which land outside the training split. With
        # almost no brand signal the model fell back on substrings, and "com"/"net" lean
        # Utilities because the ISP population owns them: AMAZON.CA.COM predicted
        # Utilities, and NETFLIX.COM predicted Utilities at 0.88 (the "net" in AireNet,
        # Astral Internet, Storm Internet). "Amzn Mktp" is the form Canadian statements
        # actually print, and it was absent entirely.
        "Amazon", "Amzn Mktp", "eBay", "Costco",
    ],
    "Utilities": [
        "Bell Aliant", "Rogers Ignite", "Shaw Mobile", "Telus Mobility",
        "Virgin Mobile Canada", "Northwestel", "Tbaytel", "Coextro", "Start.ca",
        "Acanac", "VMedia", "Yak Communications", "Comwave", "Primus Canada",
        "Just Energy", "Rite Rate Energy", "Planet Energy", "Summitt Energy",
        "Enercare", "Reliance Home Comfort", "Toronto Water", "EPCOR Water",
        "Halifax Water", "City Water Utility", "Yukon Energy", "NWT Power",
        "Qulliq Energy", "Maritime Electric", "SaskWater", "Energir", "Gazifere",
        "Superior Propane", "Sparlings Propane", "Xplore Internet", "Starlink Canada",
        "Google Fi", "Mint Mobile", "Boost Mobile", "Cricket Wireless",
        "US Cellular", "Frontier Communications", "Altice", "Breezeline",
    ],
    "Health": [
        "Pharmaprix", "PharmaChoice", "Value Drug Mart", "Medicine Shoppe",
        "Costco Optical", "Loblaw Pharmacy", "Metro Pharmacy", "Sobeys Pharmacy",
        "CVS Pharmacy", "Walgreens", "Rite Aid", "GNC", "Popeyes Supplements",
        "Nutrition House", "Vitamin Shoppe", "Bayshore HealthCare", "Nurse Next Door",
        "Telus Health", "Maple Virtual Care", "Felix Health", "Dialogue Health",
        "Altima Dental", "123Dentist", "Dentistry on Dundas", "Smile Direct Club",
        "Clearly Contacts", "Coastal Contacts", "FYidoctors", "Vision Source",
        "Image Optometry", "New Look Eyewear", "Bonlook", "Warby Parker",
        "Sport Physio", "Lifemark Physiotherapy", "pt Health", "CBI Health",
        "Shouldice Hospital", "Cleveland Clinic Canada", "Medisys Health",
        "Copeman Healthcare", "Headspace", "Calm", "BetterHelp", "Talkspace",
        "Peloton", "ClassPass", "Goodlife Express", "Fit Body Boot Camp",
        "Barre3", "Club16 Trevor Linden", "Altea Active", "The Fitness Depot",
    ],
    "Entertainment": [
        "Crunchyroll", "BritBox", "Peacock", "Showtime", "Starz", "AMC Plus",
        "Tidal", "Deezer", "SiriusXM", "Kobo", "Scribd", "Epic Games",
        "Riot Games", "Roblox", "Electronic Arts", "Ubisoft", "Blizzard",
        "Humble Bundle", "GOG", "Origin", "Battle.net", "Nintendo Switch Online",
        "PlayStation Plus", "Xbox Game Pass", "Eventbrite", "Live Nation", "AXS",
        "Vivid Seats", "Ripleys Aquarium", "Canadas Wonderland", "La Ronde",
        "African Lion Safari", "Ontario Science Centre", "Royal Ontario Museum",
        "Art Gallery of Ontario", "Casa Loma", "Hockey Hall of Fame",
        "Vancouver Aquarium", "Calgary Zoo", "Granville Island", "CN Tower",
        "Whistler Blackcomb", "Blue Mountain Resort", "Mont Tremblant",
        "Sunshine Village", "Lake Louise Ski", "Big White", "Sun Peaks",
        "Cineplex Store", "Rec Room Arcade", "Bowlerama", "Splitsville",
        "Topgolf", "Activate Games", "Rebounderz",
    ],
    "Home": [
        "Timber Mart", "Castle Building Centres", "Windsor Plywood", "Preston Hardware",
        "Bed Bath & Beyond", "Elte Furniture", "Simons Maison", "CF Interiors",
        "Behr Paint", "Para Paints", "Sico Paint", "Rust-Oleum Store",
        "Home Outfitters", "Bouclair Home", "Ashley HomeStore", "La-Z-Boy",
        "Bombay Company", "Pier 1 Imports", "HomeGoods", "Sleep Country Canada",
        "Mattress Mart", "Casper Sleep", "Douglas Mattress", "Silk & Snow",
        "Nordik Windows", "Centennial Windows", "Ecoline Windows", "Sunspace",
        "Lumber Yard Co", "Nortek Home", "Tap Hardware", "Bath Depot",
        "Taps Bath", "Ciot Tile", "Olympia Tile", "Euro Tile Stone",
        "Alexanian Carpet", "End of the Roll", "Carpet One", "Flooring Superstores",
    ],
    "Services": [
        "Google Workspace", "Microsoft OneDrive", "Zoom", "Slack", "Canva", "Figma",
        "Grammarly", "LastPass", "NordVPN", "ExpressVPN", "Surfshark", "Mailchimp",
        "Substack", "Medium", "Coursera", "Udemy", "Skillshare", "MasterClass",
        "Duolingo", "Babbel", "Chegg", "LinkedIn Learning", "Xero", "QuickBooks",
        "FreshBooks", "Wave Accounting", "UFile", "Wealthsimple Tax", "Stamps.com",
        "DHL Express", "Canpar Express", "Loomis Express", "U-Haul", "PODS Moving",
        "Two Small Men", "1-800-GOT-JUNK", "Abell Pest Control", "Mr Rooter",
        "Roto-Rooter", "TaskRabbit", "HomeStars", "Handy Services", "Rentokil",
        "Valvoline Instant Oil", "Great Canadian Oil Change", "Tirecraft",
        "Docteur du Pare-Brise", "Speedy Glass", "Boyd Autobody", "CARSTAR",
        "Mister Car Wash", "Co-op Car Wash", "Bubbles Car Wash", "Petro Wash",
        "Chatters Hair Salon", "Rapunzel Salon", "Hairhouse", "Bar Burrito Salon",
        "Cuts by Us", "Beaners Fun Cuts", "MyCleaners", "Sketchley Cleaners",
        "Pressed Dry Cleaning", "Dry Clean Depot",
    ],
    "Financial": [
        "Robinhood", "Coinbase", "Binance", "Kraken", "Shakepay", "Newton Crypto",
        "Bitbuy", "Stripe", "Square", "Venmo", "Zelle", "Wise Transfer",
        "Remitly", "Western Union", "MoneyGram", "Klarna", "Afterpay", "Affirm",
        "Sezzle", "Equifax", "TransUnion", "Credit Karma", "Allstate Insurance",
        "State Farm", "Geico", "Progressive Insurance", "RSA Insurance",
        "Definity Insurance", "Sonnet Insurance", "Onlia Insurance",
        "CAA Insurance", "Square One Insurance", "Apollo Insurance",
        "Johnson Insurance", "TD Waterhouse", "BMO Nesbitt Burns",
        "CIBC Investors Edge", "National Bank Direct", "Raymond James",
        "Edward Jones", "IG Wealth Management", "Investors Group", "Assante Wealth",
        "Mackenzie Investments", "Fidelity Canada", "Vanguard Canada",
        "BlackRock iShares", "Purpose Investments", "Horizons ETFs",
        "Canada Deposit Insurance", "Home Trust", "Equitable Bank",
        "Motusbank", "Alterna Savings", "Conexus Credit Union", "Affinity Credit Union",
        "First West Credit Union", "Prospera Credit Union", "Libro Credit Union",
    ],
    "Other": [
        "Service Nova Scotia", "Service PEI", "ServiceOntario Kiosk",
        "Registry Alberta", "Access Nova Scotia", "Insurance Corporation BC",
        "Revenu Quebec", "City of Edmonton", "City of Winnipeg", "City of Halifax",
        "City of Montreal", "City of Mississauga", "City of Surrey",
        "Regional Municipality", "Township Office", "Public Health Agency",
        "Canadian Blood Services", "Hospital Foundation", "Ronald McDonald House",
        "Make-A-Wish Canada", "Big Brothers Big Sisters", "Boys and Girls Clubs",
        "Kids Help Phone", "Alzheimer Society", "Diabetes Canada",
        "Canadian Mental Health", "Nature Canada", "Ducks Unlimited Canada",
        "Evergreen Foundation", "Tree Canada", "War Amps", "Royal Canadian Legion",
        "Terry Fox Foundation", "Princess Margaret Cancer", "St John Ambulance",
        "Mennonite Central Committee", "Development and Peace", "Islamic Relief",
        "Jewish Federation", "Sikh Nation", "Toronto Zoo Donation",
        "GoFundMe Campaign", "Kickstarter Pledge", "Indiegogo", "Patreon Membership",
    ],
}

# Same brand recorded under two categories, or plainly mislabeled by the parquet mining.
# Applied after every source is merged so the union carries one label per merchant.
LABEL_FIXES: dict[str, str] = {
    # mined from a US dataset where a grocer's cafe counter dominated
    "Safeway": "Groceries",
    "Whole Foods": "Groceries",
    "Trader Joe's": "Groceries",
    "Walmart Supercenter": "Groceries",
    # cross-category duplicates of the same brand
    "Lowes": "Home",
    "Lowe's": "Home",
    "Home Depot": "Home",
    "The Home Depot": "Home",
    "Costco": "Shopping",
    "Costco Wholesale": "Shopping",
    "UPS": "Services",
    "UPS Store": "Services",
    # government auto insurers are insurance products, not civic services
    "ICBC": "Financial",
    "SGI": "Financial",
    "Manitoba Public Insurance": "Financial",
}

# Digit-stripping in the original mining mangled these names.
NAME_FIXES: dict[str, str] = {
    "-Eleven": "7-Eleven",
    "Saks Off th": "Saks Off 5th",
    "Hour Fitness": "24 Hour Fitness",
}
